version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: 'mysql'
    image: 'mysql:5.7'
    environment:
      - 'MYSQL_DATABASE=demodb'
      - 'MYSQL_ROOT_PASSWORD=11111111'
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=11111111 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:


